##Don't touch anything bellow.
Placeholders:
  ServerName:
    GUI:
      Material: NETHER_STAR
      Name: "&6Server Name"
    DATA:
      Type: FILE #Types: PLACEHOLDER / FILE
      File: "/plugins/TabList/tablist.yml"
      Variable: "header"
    Value: "Advanced setups, please run /setup to get started!"
GuiSettings:
  Title: "ServerSetups.net Assist"
  PlaceholderId: "ServerSetups"
  PlaceholderSet: "&eYou are setting the %placeholder% placeholder!"
  PlaceholderDone: "&eYou set the %placeholder% placeholder to %set-to%" ##Placeholders: %placeholder%, %set-to%
  Previous:
    Material: PAPER
    Name: "&c&lPrevious"
  Next:
    Material: PAPER
    Name: "&c&lNext"